### ISSUE TITLE
Failed to merge error

### ISSUE THREAD

**Issue by axblain** [hudec117/sf-user-perm-report#45] opened 2022-08-26 11:07 UTC
**Describe the bug**
Failed to merge error. Tried on 2 users. Tried on Classic and LEX.

**To Reproduce**
1. Go to user
2. Click on "Open permission report" button 
3. Wait
6. See error "Failed to merge, see console for details."

**Expected behavior**
First time I use the extension. Extension did sound promising but this was disappointing.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser type and version [e.g. Chrome 88.0.4324.150]
 - Extension version [e.g. 1.0.0]

**Comment by hudec117** [comment] 2022-08-31 15:44
Does anything come up in the console regarding this error?

Is there anything special about your users or their profile, permission sets or permission set groups?

**Comment by axblain** [comment] 2022-09-01 08:52
I haven't checked the console (I don't know how it works or what to look
for).

Other than being complex permissions (which is the reason to use the
extension), nothing strikes to me as "special"

**Comment by aknight1157** [comment] 2024-02-08 13:51
@hudec117 I am running into this same issue. I don't know how to access the console to see error details. It seems to be happening on any user in some of my orgs that have complex permissions. The report works in the same browser in a different org with simple permissions.

**Comment by hudec117** [comment] 2024-02-10 00:12
@aknight1157 could you try removing all the permission sets from the user and running the report? If it works, that would indicate the issue is with one of the permission sets. If not, then it means it may be the profile.

**Comment by hudec117** [comment] 2024-02-11 18:06
I have been able to replicate this issue by putting a managed Permission Set into a permission set group and then trying to run the report. Is this the case in your scenario?

**Comment by hudec117** [comment] 2024-02-28 23:58
This should be fixed as of 1.2.4, in the process of being published to the Chrome Web Store. If you find it still doesn't work with the update, feel free to re-open!

**Closed by hudec117** 2024-02-28 23:58 UTC
Labels: bug
